# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  # Required for actions/checkout
  contents: read
  # Required for OIDC authentication to PyPI
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Patch README.md links
      # Replace relative README links like
      # [`examples/basic_site.py`](./examples/basic_site.py)
      # with
      # [`examples/basic_site.py`](https://github.com/pydsigner/anchovy_css/blob/master/examples/basic_site.py)
      run: sed -E -i -e "s:\[(.*)\]\(\./(.*)\):[\1](https\://github.com/pydsigner/anchovy_css/blob/master/\2):g" README.md
    - name: Build package
      # https://stackoverflow.com/a/15988793/1795505
      run: |
        SETUPTOOLS_SCM_PRETEND_VERSION=${GITHUB_REF##*/v} python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
